### ISSUE TITLE
Please do not set outline: 0; 😢😢😢

### ISSUE THREAD

**Issue by yamanoku** [nju33/react-dou#35]
- https://github.com/nju33/react-dou/blob/168c040b556b831be0b8ad501fd56455b59cf7d6/src/dou.organism/button.atom.tsx#L8

https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html

If you don't like to have focus when mouse clicking ... 

- Please use `what-input`
  - https://github.com/ten1seven/what-input
  - This is what you can give a style to when you are mouse and keyboard, and when you touch.

**Comment by nju33** [comment]
please as following

```js
import {Button} from 'react-dou';

const MyButton = styled(Button)`
  outline: 1px solid blue;
`;
```

**Comment by nju33** [comment]
reversed

```js
import {Button} from 'react-dou';

const MyButton = styled(Button)`
  outline: none;
`;

<Dou components={{Button: MyButton}} {...props} />
```

**Comment by yamanoku** [comment]
Thanks !!!!!!!!!!!!!!
